# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d689b98b4d97b931d5298f6a70453366f5f3ba27057e5140446dd458dc5947f39b6cdc7bfa43ba475f31783dc416882080a4498677d6ba0e76eb45491c8b7042

test:
  secret_key_base: 3554a4f5cb942565d5ba7f8037c7853202e9df8b3edc5a2b0525ba684be594d67ee53507a7dec0c2f5ce2411e173beae724314b525296f70ee63e7dc612ec520

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
